import type { Marker } from "./types.ts";

/**
 * Surface cues. Generation markers can name a style band only in combination
 * (see the decision policy). Family markers move the house-style score and
 * do not, by themselves, name a checkpoint.
 */
export const MARKERS: readonly Marker[] = [
  // Early ChatGPT / GPT-3.5
  {
    id: "gpt35-certainly",
    re: /\bcertainly[!.,]/i,
    weight: 2.6,
    family: "gpt",
    model: "gpt-3.5",
    specificity: "generation",
    note: "Sycophantic opener",
  },
  {
    id: "gpt35-as-an-ai",
    re: /\bas an ai language model\b/i,
    weight: 3.4,
    family: "gpt",
    model: "gpt-3.5",
    specificity: "generation",
    note: "Early assistant self-description",
  },
  {
    id: "gpt35-cutoff",
    re: /\bknowledge cutoff\b/i,
    weight: 2.4,
    family: "gpt",
    model: "gpt-3.5",
    specificity: "generation",
    note: "Knowledge-cutoff disclaimer",
  },
  {
    id: "gpt35-no-opinions",
    re: /\bi don'?t have (?:personal |strong )?opinions\b/i,
    weight: 2.2,
    family: "gpt",
    model: "gpt-3.5",
    specificity: "generation",
    note: "Opinion disclaimer",
  },
  {
    id: "gpt35-hope",
    re: /\bi hope this helps\b/i,
    weight: 2.4,
    family: "gpt",
    model: "gpt-3.5",
    specificity: "generation",
    note: "Classic closer",
  },

  // GPT-4 brochure diction
  {
    id: "gpt4-delve",
    re: /\bdelve (?:into|deeper)\b/i,
    weight: 2.4,
    family: "gpt",
    model: "gpt-4",
    specificity: "generation",
    note: "Stock GPT verb",
  },
  {
    id: "gpt4-tapestry",
    re: /\btapestry\b/i,
    weight: 2.2,
    family: "gpt",
    model: "gpt-4",
    specificity: "generation",
    note: "Overused metaphor",
  },
  {
    id: "gpt4-landscape",
    re: /\blandscape of\b/i,
    weight: 2.0,
    family: "gpt",
    model: "gpt-4",
    specificity: "generation",
    note: "Stock metaphor",
  },
  {
    id: "gpt4-realm",
    re: /\bin the realm of\b/i,
    weight: 2.0,
    family: "gpt",
    model: "gpt-4",
    specificity: "generation",
    note: "Padded prepositional",
  },
  {
    id: "gpt4-role",
    re: /\bplays a (?:crucial|vital|pivotal|key) role\b/i,
    weight: 2.2,
    family: "gpt",
    model: "gpt-4",
    specificity: "generation",
    note: "Empty emphasis",
  },
  {
    id: "gpt4-important",
    re: /\bit'?s important to (?:note|remember|understand|consider)\b/i,
    weight: 2.0,
    family: "gpt",
    model: "gpt-4",
    specificity: "generation",
    note: "Teacher hedge",
  },
  {
    id: "gpt4-multifaceted",
    re: /\bmultifaceted\b/i,
    weight: 1.8,
    family: "gpt",
    model: "gpt-4",
    specificity: "generation",
    note: "Inflated adjective",
  },
  {
    id: "gpt4-comprehensive",
    re: /\bcomprehensive (?:overview|guide|understanding)\b/i,
    weight: 2.0,
    family: "gpt",
    model: "gpt-4",
    specificity: "generation",
    note: "Brochure diction",
  },
  {
    id: "gpt4-nestled",
    re: /\bnestled\b/i,
    weight: 1.8,
    family: "gpt",
    model: "gpt-4",
    specificity: "generation",
    note: "Travel-copy adjective",
  },
  {
    id: "gpt4-evolving",
    re: /\bin the ever-evolving\b/i,
    weight: 2.2,
    family: "gpt",
    model: "gpt-4",
    specificity: "generation",
    note: "Intro cliché",
  },
  {
    id: "gpt4-testament",
    re: /\ba testament to\b/i,
    weight: 1.8,
    family: "gpt",
    model: "gpt-4",
    specificity: "generation",
    note: "Stock idiom",
  },
  {
    id: "gpt4-shed",
    re: /\bshed light on\b/i,
    weight: 1.8,
    family: "gpt",
    model: "gpt-4",
    specificity: "generation",
    note: "Stock idiom",
  },
  {
    id: "gpt4-whether",
    re: /\bwhether you'?re\b/i,
    weight: 1.6,
    family: "gpt",
    model: "gpt-4",
    specificity: "generation",
    note: "Listicle pivot",
  },
  {
    id: "gpt4-both-sides",
    re: /\bon (?:the )?one hand\b[\s\S]{0,80}\bon the other\b/i,
    weight: 1.8,
    family: "gpt",
    model: "gpt-4",
    specificity: "generation",
    note: "Both-sides scaffold",
  },

  // Later ChatGPT / GPT-4o voice — shorter, less brochure
  {
    id: "gpt4o-short",
    re: /\b(?:here'?s|the) short version\b/i,
    weight: 2.2,
    family: "gpt",
    model: "gpt-4o",
    specificity: "generation",
    note: "Short-version frame",
  },
  {
    id: "gpt4o-quick",
    re: /\bquick (?:take|version)\b/i,
    weight: 2.0,
    family: "gpt",
    model: "gpt-4o",
    specificity: "generation",
    note: "Quick-take frame",
  },
  {
    id: "gpt4o-tldr",
    re: /\btl;dr\b/i,
    weight: 1.8,
    family: "gpt",
    model: "gpt-4o",
    specificity: "generation",
    note: "TL;DR label",
  },
  {
    id: "gpt4o-got-it",
    re: /\bgot it[,.—-]/i,
    weight: 1.8,
    family: "gpt",
    model: "gpt-4o",
    specificity: "generation",
    note: "Conversational ack",
  },
  {
    id: "gpt4o-want",
    re: /\bwant me to\b/i,
    weight: 1.8,
    family: "gpt",
    model: "gpt-4o",
    specificity: "generation",
    note: "Offer to continue",
  },
  {
    id: "gpt4o-clearer",
    re: /\bhere'?s a clearer\b/i,
    weight: 2.0,
    family: "gpt",
    model: "gpt-4o",
    specificity: "generation",
    note: "Reframe opener",
  },

  // OpenAI reasoning models
  {
    id: "o-work",
    re: /\blet me work through\b/i,
    weight: 2.6,
    family: "gpt",
    model: "o-series",
    specificity: "generation",
    note: "Reasoning opener",
  },
  {
    id: "o-reason",
    re: /\b(?:let'?s|i'll) reason\b/i,
    weight: 2.4,
    family: "gpt",
    model: "o-series",
    specificity: "generation",
    note: "Explicit reasoning",
  },
  {
    id: "o-backwards",
    re: /\bworking backwards\b/i,
    weight: 2.2,
    family: "gpt",
    model: "o-series",
    specificity: "generation",
    note: "Backward pass",
  },
  {
    id: "o-insight",
    re: /\bthe key insight\b/i,
    weight: 2.0,
    family: "gpt",
    model: "o-series",
    specificity: "generation",
    note: "Insight stamp",
  },
  {
    id: "o-assume",
    re: /\bassumptions?\s*:/i,
    weight: 2.2,
    family: "gpt",
    model: "o-series",
    specificity: "generation",
    note: "Assumption list",
  },
  {
    id: "o-therefore",
    re: /\btherefore,\s+(?:we|the|this|it)\b/i,
    weight: 1.6,
    family: "gpt",
    model: "o-series",
    specificity: "generation",
    note: "Deductive hinge",
  },

  // Shared OpenAI manners — family only
  {
    id: "gpt-of-course",
    re: /\bof course[!.,]/i,
    weight: 1.2,
    family: "gpt",
    specificity: "family",
    note: "Agreeable opener",
  },
  {
    id: "gpt-absolutely",
    re: /\babsolutely[!.,]/i,
    weight: 1.0,
    family: "gpt",
    specificity: "family",
    note: "Agreeable opener",
  },
  {
    id: "gpt-great-question",
    re: /\bgreat question\b/i,
    weight: 2.2,
    family: "gpt",
    specificity: "family",
    note: "Assistant flattery",
  },
  {
    id: "gpt-happy-to",
    re: /\bi'?d be happy to\b/i,
    weight: 1.6,
    family: "gpt",
    specificity: "family",
    note: "Assistant offer",
  },
  {
    id: "gpt-let-me-know",
    re: /\blet me know if (?:you )?(?:need|have|would)\b/i,
    weight: 1.4,
    family: "gpt",
    specificity: "family",
    note: "Support closer",
  },
  {
    id: "gpt-feel-free",
    re: /\bfeel free to\b/i,
    weight: 0.8,
    family: "gpt",
    specificity: "family",
    note: "Support closer",
  },
  {
    id: "gpt-robust",
    re: /\brobust\b/i,
    weight: 0.45,
    family: "gpt",
    specificity: "family",
    note: "Corporate filler",
  },
  {
    id: "gpt-leverage",
    re: /\bleverage\b/i,
    weight: 0.4,
    family: "gpt",
    specificity: "family",
    note: "Corporate filler",
  },
  {
    id: "gpt-foster",
    re: /\bfoster(?:s|ing)?\b/i,
    weight: 0.45,
    family: "gpt",
    specificity: "family",
    note: "Corporate filler",
  },
  {
    id: "gpt-vibrant",
    re: /\bvibrant\b/i,
    weight: 0.4,
    family: "gpt",
    specificity: "family",
    note: "Brochure adjective",
  },
  {
    id: "gpt-underscore",
    re: /\bunderscore(?:s|d)?\b/i,
    weight: 0.5,
    family: "gpt",
    specificity: "family",
    note: "Essay verb",
  },
  {
    id: "gpt-navigate",
    re: /\bnavigat(?:e|ing) the\b/i,
    weight: 0.8,
    family: "gpt",
    specificity: "family",
    note: "Stock verb",
  },
  {
    id: "gpt-conclusion",
    re: /\bin conclusion\b/i,
    weight: 0.9,
    family: "gpt",
    specificity: "family",
    note: "Essay closer",
  },

  // Claude 3
  {
    id: "c3-careful",
    re: /\bi want to be (?:careful|honest|precise|clear)\b/i,
    weight: 2.6,
    family: "claude",
    model: "claude-3",
    specificity: "generation",
    note: "Claude caution",
  },
  {
    id: "c3-worth",
    re: /\bit'?s worth (?:sitting with|lingering|being precise)\b/i,
    weight: 2.4,
    family: "claude",
    model: "claude-3",
    specificity: "generation",
    note: "Reflective hedge",
  },
  {
    id: "c3-tension",
    re: /\bthere'?s a (?:real )?(?:tension|trade-?off|nuance)\b/i,
    weight: 2.2,
    family: "claude",
    model: "claude-3",
    specificity: "generation",
    note: "Nuance framing",
  },
  {
    id: "c3-think",
    re: /\blet me (?:think|sit) (?:through|with)\b/i,
    weight: 2.0,
    family: "claude",
    model: "claude-3",
    specificity: "generation",
    note: "Thinking-aloud",
  },
  {
    id: "c3-wary",
    re: /\bi(?:'d| would) (?:push back|be cautious|be wary)\b/i,
    weight: 2.0,
    family: "claude",
    model: "claude-3",
    specificity: "generation",
    note: "Gentle dissent",
  },
  {
    id: "c3-precise",
    re: /\bif i'?m being (?:precise|honest|careful)\b/i,
    weight: 2.2,
    family: "claude",
    model: "claude-3",
    specificity: "generation",
    note: "Self-qualifying",
  },
  {
    id: "c3-sit",
    re: /\bhappy to (?:sit with|go deeper|unpack)\b/i,
    weight: 2.4,
    family: "claude",
    model: "claude-3",
    specificity: "generation",
    note: "Collaborative offer",
  },
  {
    id: "c3-honest",
    re: /\bthe honest (?:version|answer)\b/i,
    weight: 1.8,
    family: "claude",
    model: "claude-3",
    specificity: "generation",
    note: "Candor frame",
  },
  {
    id: "c3-something",
    re: /\bthere'?s something (?:slightly|quietly|oddly)\b/i,
    weight: 1.8,
    family: "claude",
    model: "claude-3",
    specificity: "generation",
    note: "Literary hedge",
  },

  // Claude 4 — more direct, still the same house
  {
    id: "c4-direct",
    re: /\bi'?ll be direct\b/i,
    weight: 2.6,
    family: "claude",
    model: "claude-4",
    specificity: "generation",
    note: "Direct frame",
  },
  {
    id: "c4-pad",
    re: /\bi won'?t (?:pad|dress this)\b/i,
    weight: 2.2,
    family: "claude",
    model: "claude-4",
    specificity: "generation",
    note: "Anti-preamble",
  },
  {
    id: "c4-separate",
    re: /\bworth separating\b/i,
    weight: 2.2,
    family: "claude",
    model: "claude-4",
    specificity: "generation",
    note: "Split the question",
  },
  {
    id: "c4-two",
    re: /\btwo (?:different|separate) questions\b/i,
    weight: 2.0,
    family: "claude",
    model: "claude-4",
    specificity: "generation",
    note: "Question split",
  },
  {
    id: "c4-answer",
    re: /\bthe direct (?:answer|version)\b/i,
    weight: 2.2,
    family: "claude",
    model: "claude-4",
    specificity: "generation",
    note: "Direct answer",
  },
  {
    id: "c4-do",
    re: /\bhere'?s what i'?d (?:actually )?do\b/i,
    weight: 2.0,
    family: "claude",
    model: "claude-4",
    specificity: "generation",
    note: "Action frame",
  },
  {
    id: "c4-preamble",
    re: /\bi'?ll skip the preamble\b/i,
    weight: 2.4,
    family: "claude",
    model: "claude-4",
    specificity: "generation",
    note: "Skip the preamble",
  },

  {
    id: "c-that-said",
    re: /\bthat said\b/i,
    weight: 0.35,
    family: "claude",
    specificity: "family",
    note: "Turn hedge",
  },
  {
    id: "c-genuinely",
    re: /\bgenuinely\b/i,
    weight: 0.25,
    family: "claude",
    specificity: "family",
    note: "Soft intensifier",
  },

  // Gemini 1.5 class
  {
    id: "g15-breakdown",
    re: /\bhere'?s a breakdown\b/i,
    weight: 2.8,
    family: "gemini",
    model: "gemini-1.5",
    specificity: "generation",
    note: "Breakdown cue",
  },
  {
    id: "g15-takeaways",
    re: /\bkey takeaways?\b/i,
    weight: 2.6,
    family: "gemini",
    model: "gemini-1.5",
    specificity: "generation",
    note: "Takeaway header",
  },
  {
    id: "g15-explore",
    re: /\blet'?s (?:explore|break (?:this )?down|dive in)\b/i,
    weight: 2.0,
    family: "gemini",
    model: "gemini-1.5",
    specificity: "generation",
    note: "Tour-guide opener",
  },
  {
    id: "g15-help",
    re: /\bi can help with that\b/i,
    weight: 2.2,
    family: "gemini",
    model: "gemini-1.5",
    specificity: "generation",
    note: "Assistant ack",
  },
  {
    id: "g15-options",
    re: /\bhere are some options\b/i,
    weight: 2.2,
    family: "gemini",
    model: "gemini-1.5",
    specificity: "generation",
    note: "Options list",
  },
  {
    id: "g15-quick",
    re: /\bquick answer\b/i,
    weight: 1.6,
    family: "gemini",
    model: "gemini-1.5",
    specificity: "generation",
    note: "Quick-answer header",
  },
  {
    id: "g15-summarize",
    re: /\bto summarize\b/i,
    weight: 1.4,
    family: "gemini",
    model: "gemini-1.5",
    specificity: "generation",
    note: "Recap header",
  },
  {
    id: "g15-steps",
    re: /\bstep[- ]by[- ]step\b/i,
    weight: 1.4,
    family: "gemini",
    model: "gemini-1.5",
    specificity: "generation",
    note: "How-to frame",
  },
  {
    id: "g15-pros",
    re: /\bpros and cons\b/i,
    weight: 1.3,
    family: "gemini",
    model: "gemini-1.5",
    specificity: "generation",
    note: "Comparison frame",
  },

  // Gemini 2.5 class — bold outlines, less of the 1.5 tour script
  {
    id: "g25-means",
    re: /\bwhat this means\b/i,
    weight: 2.2,
    family: "gemini",
    model: "gemini-2.5",
    specificity: "generation",
    note: "Implication header",
  },
  {
    id: "g25-glance",
    re: /\bat a glance\b/i,
    weight: 1.8,
    family: "gemini",
    model: "gemini-2.5",
    specificity: "generation",
    note: "At-a-glance chip",
  },

  // Grok 3
  {
    id: "k3-look",
    re: /\blook,\s/i,
    weight: 1.7,
    family: "grok",
    model: "grok-3",
    specificity: "generation",
    note: "Direct address",
  },
  {
    id: "k3-thing",
    re: /\bhere'?s the (?:thing|deal)\b/i,
    weight: 2.3,
    family: "grok",
    model: "grok-3",
    specificity: "generation",
    note: "Street thesis",
  },
  {
    id: "k3-hot",
    re: /\bhot take\b/i,
    weight: 2.2,
    family: "grok",
    model: "grok-3",
    specificity: "generation",
    note: "Opinion cue",
  },
  {
    id: "k3-pretend",
    re: /\bi'?m not going to (?:pretend|dress this up)\b/i,
    weight: 2.4,
    family: "grok",
    model: "grok-3",
    specificity: "generation",
    note: "Anti-corporate",
  },
  {
    id: "k3-boring",
    re: /\bthe boring (?:answer|truth)\b/i,
    weight: 2.2,
    family: "grok",
    model: "grok-3",
    specificity: "generation",
    note: "Deflation",
  },
  {
    id: "k3-nah",
    re: /\bnah,\s/i,
    weight: 1.6,
    family: "grok",
    model: "grok-3",
    specificity: "generation",
    note: "Conversational no",
  },

  // Grok 4 — still sided, less of the meme register
  {
    id: "k4-constraint",
    re: /\bthe actual constraint\b/i,
    weight: 2.4,
    family: "grok",
    model: "grok-4",
    specificity: "generation",
    note: "Constraint frame",
  },
  {
    id: "k4-ship",
    re: /\bi'?d ship\b/i,
    weight: 2.2,
    family: "grok",
    model: "grok-4",
    specificity: "generation",
    note: "Ship frame",
  },
  {
    id: "k4-price",
    re: /\bthe price of being wrong\b/i,
    weight: 2.2,
    family: "grok",
    model: "grok-4",
    specificity: "generation",
    note: "Cost frame",
  },
  {
    id: "k4-actually",
    re: /\bwhat i'?d actually (?:do|ship|pick)\b/i,
    weight: 2.0,
    family: "grok",
    model: "grok-4",
    specificity: "generation",
    note: "Actual pick",
  },
  {
    id: "k4-nontrivial",
    re: /\bnon-trivial\b/i,
    weight: 0.5,
    family: "grok",
    specificity: "family",
    note: "Technical hedge",
  },

  {
    id: "k-honestly",
    re: /\bhonestly[, ]/i,
    weight: 0.45,
    family: "grok",
    specificity: "family",
    note: "Candid adverb",
  },
  {
    id: "k-yeah",
    re: /\byeah,\s/i,
    weight: 0.35,
    family: "grok",
    specificity: "family",
    note: "Conversational yes",
  },

  // DeepSeek V3
  {
    id: "ds-keypoints",
    re: /\bhere are some key points\b/i,
    weight: 2.6,
    family: "deepseek",
    model: "deepseek-v3",
    specificity: "generation",
    note: "Key-points inventory",
  },
  {
    id: "ds-following",
    re: /\bthe following are some\b/i,
    weight: 2.2,
    family: "deepseek",
    model: "deepseek-v3",
    specificity: "generation",
    note: "Inventory opener",
  },
  {
    id: "ds-additionally",
    re: /\badditionally, consider\b/i,
    weight: 2.4,
    family: "deepseek",
    model: "deepseek-v3",
    specificity: "generation",
    note: "Additional inventory",
  },
  {
    id: "ds-context",
    re: /\bin this (?:context|article), it is\b/i,
    weight: 1.8,
    family: "deepseek",
    model: "deepseek-v3",
    specificity: "generation",
    note: "Context preamble",
  },

  // DeepSeek-R1 reasoning trace
  {
    id: "r1-think",
    re: /<\/?think>/i,
    weight: 4.6,
    family: "deepseek",
    model: "deepseek-r1",
    specificity: "generation",
    note: "Reasoning-trace tag",
  },
  {
    id: "r1-reconsider",
    re: /\blet me reconsider\b/i,
    weight: 2.4,
    family: "deepseek",
    model: "deepseek-r1",
    specificity: "generation",
    note: "Reconsider step",
  },
  {
    id: "r1-alternatively",
    re: /\balternatively, (?:one|we|if)\b/i,
    weight: 1.8,
    family: "deepseek",
    model: "deepseek-r1",
    specificity: "generation",
    note: "Branching alternative",
  },
  {
    id: "r1-asks",
    re: /\bthe problem asks\b/i,
    weight: 1.8,
    family: "deepseek",
    model: "deepseek-r1",
    specificity: "generation",
    note: "Problem restatement",
  },

  // Generic machine transitions. Essay words alone are not a house style.
  {
    id: "ai-furthermore",
    re: /\bfurthermore\b/i,
    weight: 0.7,
    specificity: "ai",
    note: "Essay transition",
  },
  {
    id: "ai-moreover",
    re: /\bmoreover\b/i,
    weight: 0.7,
    specificity: "ai",
    note: "Essay transition",
  },
  {
    id: "ai-additionally",
    re: /\badditionally\b/i,
    weight: 0.5,
    specificity: "ai",
    note: "Essay transition",
  },
  {
    id: "ai-not-only",
    re: /\bnot only\b[\s\S]{0,40}\bbut also\b/i,
    weight: 0.8,
    specificity: "ai",
    note: "Correlative parallelism",
  },
  {
    id: "ai-cannot-browse",
    re: /\bi (?:cannot|can't) (?:browse|access) the internet\b/i,
    weight: 1.6,
    family: "gpt",
    specificity: "family",
    note: "Capability disclaimer",
  },

  // Human
  {
    id: "h-idk",
    re: /\bidk\b/i,
    weight: 2.2,
    family: "human",
    specificity: "human",
    note: "Typed abbreviation",
  },
  {
    id: "h-chat",
    re: /\blmao\b|\blol\b|\btbh\b|\bimo\b/i,
    weight: 1.8,
    family: "human",
    specificity: "human",
    note: "Chat register",
  },
  {
    id: "h-reduce",
    re: /\b(?:gonna|wanna|gotta|kinda|sorta)\b/i,
    weight: 1.5,
    family: "human",
    specificity: "human",
    note: "Spoken reduction",
  },
  {
    id: "h-pause",
    re: /\b(?:um+|uh+|erm)\b/i,
    weight: 2.0,
    family: "human",
    specificity: "human",
    note: "Filled pause",
  },
  {
    id: "h-typo",
    re: /\b(?:reciept|definately|seperate|occured|wierd|alot|becuase|thier|untill|teh)\b/i,
    weight: 2.4,
    family: "human",
    specificity: "human",
    note: "Typo",
  },
];

export function generationMarkersFor(model: string): Marker[] {
  return MARKERS.filter((marker) => marker.model === model && marker.specificity === "generation");
}
